#!/bin/sh

ME=js
PJS_DIR=$HOME/Dev/Mozilla/mozilla-inbound/objdir-opt-js/js/src/shell
# PJS_DIR=$HOME/Dev/Mozilla/iontrail/objdir-dbg-js
# PJS_DIR=$HOME/Dev/Mozilla/iontrail/objdir-opt-js
exec $PJS_DIR/$ME "$@"
