#!/bin/sh

set -x
set -e

shopt -s nullglob # nullglob enables foo* expanding to empty if no matches

SRC=$1
TGT=$2

git clone $SRC $TGT

for d in compiler-rt gyp libuv llvm jemalloc rt/hoedown ; do
    SRC_D=$SRC/src/$d
    if [ -e $SRC_D ] ; then
        URL=$( cd $SRC_D && git config remote.origin.url )
        git clone --reference $SRC_D -- $URL $TGT/src/$d
    fi
done


for d in $SRC/objdir-dbgopt $SRC/objdir-dbg ; do
    mkdir -v $TGT/$(basename $d)
    if [ -e $d/dl ] ; then
       mkdir $TGT/$(basename $d)/dl
       (cd $d/dl && tar cf - .) | (cd $TGT/$(basename $d)/dl && tar xf - )
    fi
done

for d in $TGT/objdir-* ; do
    pushd $d
    rust-configure
    popd
done

pushd $TGT
git remote add  moz-gh git://github.com/rust-lang/rust.git
git remote add  pnk-gh git@github.com:pnkfelix/rust.git
git remote add huon-gh git@github.com:huonw/rust.git
git remote add alex-gh git@github.com:alexcrichton/rust.git
git remote add brsn-gh git@github.com:brson/rust.git
git remote add niko-gh git@github.com:nikomatsakis/rust.git
git remote add  pcw-gh git@github.com:pcwalton/rust.git
git remote add  cmr-gh git@github.com:cmr/rust.git
git remote add   eb-gh git@github.com:eddyb/rust.git
git remote add zwarich-gh git@github.com:zwarich/rust.git
git remote add  nrc-gh git@github.com:nick29581/rust.git
popd
